### ISSUE TITLE
Keymaps aren't attached

### ISSUE THREAD

**Issue by hinell** [theHamsta/crazy-node-movement#3]
The given config from current 0c0b49e06713e0a9164e67e71dae5643acd0341f readme doesn't attach keymaps.

```
NVIM v0.10.0-dev-daf7abbc42
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
```
nvim-treesitter: 691d732

### UPDATE
I got it working with the following config:

```lua

require "nvim-treesitter.configs".setup({
  node_movement = {
	enable=true,
	keymaps = {
	  move_up	      = "<A-k>",
	  move_down	      = "<A-j>",
	  move_left           = "<A-h>",
	  move_right          = "<A-l>",
	  swap_left           = "<A-a-h>",
	  swap_right          = "<A-a-l>",
	  select_current_node = "nn"
	},

	swappable_textobjects = {
		 "@function.outer"
		,"@parameter.inner"
		,"@statement.outer"
	},
	allow_switch_parents = false,
	allow_next_parent = false
  }
})
```

**Comment by theHamsta** [comment]
Do you have something like this in your config?
```lua
  require("nvim-treesitter.configs").setup {
    node_movement = {
      enable = true,
      highlight_current_node = true,
      keymaps = {
        move_up = "<a-k>",
        move_down = "<a-j>",
        move_left = "<a-h>",
        move_right = "<a-l>",
        swap_up = "<s-a-k>",
        swap_left = "<s-a-h>",
        swap_right = "<s-a-l>",
        select_current_node = "<cr>",
      },
      allow_switch_parents = true,
      allow_next_parent = true,
    },
}
```

I think the README misses `enable = true`

**Comment by hinell** [comment]
@theHamsta Yes, I'm having the same config, I have tried `enable=true` as well. I also tried to gather all modules into one ` require("nvim-treesitter.configs").setup ...` call, like so:
```lua
 require("nvim-treesitter.configs").setup({
   node_movement = {
     enable=true     
     ...
   },
   textobjects = {
     enable=true     
     ...
   }
})
```

but it didn't work. Meanwhile, commands like `move_up` if called directly via lua are working.

**Comment by hinell** [comment]
I think you should consider another approach for keymap setup. See [tree-climber](https://github.com/drybalka/tree-climber.nvim) for instance.

**Comment by theHamsta** [comment]
You might have problems with the alt-mappings when using neovim in terminal

**Comment by hinell** [comment]
@theHamsta Well I don't think so. I got `select_current_node` mapping working, while `<a-j>...` aren't working at all.

Btw, I also have [nvim-treesitter-texobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) installed and pending bindings ARE working ...
